"""add created_at to orders

Revision ID: 49a043c2a644
Revises: 562d0ec397c9
Create Date: 2026-02-06 12:18:33.391692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a043c2a644'
down_revision: Union[str, Sequence[str], None] = '562d0ec397c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'orders',
    sa.Column(
        'created_at',
        sa.DateTime(),
        nullable=False,
        server_default=sa.func.now()  # <-- sets a value for existing rows
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
